Pr
niharikadayama/shopping-app pull request #8
Opened 2022-01-31 04:47 UTC by niharikadayama

2022-01-31 06:29 UTC, Parth-coditas requested changes

2022-01-31 06:29 UTC, Parth-coditas commented on src/redux/shopping/reducer.tsx
> +      case actionTypes.ADD_TO_CART:
You can refactor this case as well.

```
 const item = materials.find(prod => prod.id === action.payload.id) 
        // check if item is in cart already
        const inCart = state.cart.find((item:any)=> 
        item.id === action.payload.id ? true : false
        );
```
no need to loop twice and also return true or false
as item.id === action.payload itself is a condition which will directly return true or false.

2022-01-31 06:29 UTC, Parth-coditas commented on src/screen/itemDetail/index.tsx
>      const sizeCheck = item.size
Can you find an alternative / better approach to use sizeCheck in the FlatList ?

2022-01-31 06:29 UTC, Parth-coditas commented on src/screen/details/index.tsx
>    const DataType = item.key;
Find an alternative / better approach to use DataType in the FlatList

2022-01-31 06:30 UTC, Parth-coditas commented
Also, 
keep branch names, commit messages more meaningful to explain what functionality it has, or what changes did that commit had !

2022-01-31 12:37 UTC, niharikadayama commented on package.json
> +    "react-navigation": "^4.4.4",
installed it to use switch navigator .. using createSwitchNavigator from 'react-navigation'

2022-01-31 12:42 UTC, Parth-coditas commented on package.json
> +    "react-navigation": "^4.4.4",
Switch Navigator is mostly deprecated, and you are already using react-navigation v6, so no need to install react-navigation v4 again, instead you can find an alternative to switch navigator

2022-01-31 12:47 UTC, niharikadayama commented on package.json
> +    "react-navigation": "^4.4.4",
okay got it. removed v4.

2022-01-31 12:48 UTC, niharikadayama commented on src/navigation/stackNavigation.tsx
> +      {true ? (
I was just testing something its not a part of code.

2022-02-03 07:10 UTC, Parth-coditas commented on src/screen/settings/index.tsx
> +const Settings = ({navigation}) => {
Again..Redundant code
We have navigation-service file, right ?

2022-02-07 06:04 UTC, Parth-coditas requested changes

2022-02-07 06:04 UTC, Parth-coditas commented on src/screen/support/index.tsx
> +                                  {item.subHeading.map(subHeading => (
Any specific reason to use map ? instead of flatList ?

2022-02-07 06:04 UTC, Parth-coditas commented on src/screen/itemDetail/index.tsx
> +                    navigation.navigate('wishlist', item),
use semicolon to separate lines, instead of commas

2022-02-07 10:45 UTC, merged